### ISSUE TITLE
Support of cluster

### ISSUE THREAD

**Issue by Khady** [0xffea/ocaml-redis#39]
Redis supports a cluster mode: http://redis.io/topics/cluster-spec

From what I have read yet, there is no support for cluster in the current state of `ocaml-redis`. I would like to contribute simple support for some commands (like `get`, `set`, ...). But I don't know what's the good to way to add it to the API.

One simple possibility is to follow the `ASK` or `MOVED` reply all the time. And maybe to add an option in `connect` to decide if those redirection should be followed or handled as errors.

Another possibility is to create a `ClusterClient` module with a few commands in it for now and to add the other ones later.

Would you accept a PR to add some cluster support into this library? Which API do you prefer? Any advises or hints?

For reference:
- [Redis cluster tutorial](http://redis.io/topics/cluster-tutorial)
- [Redis Cluster Specification](http://redis.io/topics/cluster-spec)
- [Redis Cluster Ruby client based on redis-rb](https://github.com/antirez/redis-rb-cluster)

**Comment by aluuu** [comment]
Hi, @Khady 

You are right, there's no support for cluster in `ocaml-redis`. I would be glad to accept PR with cluster mode support.

IMO, option with separate `ClusterClient` module would be better choice. I think that it would be easier to implement redirection and hash slots logic in separate module(s), rather than trying to rework whole `Client` module to handle this stuff.

As I see, implementations of redirection logic written in another languages (like Ruby or Python) involves exceptions. I think it would be better choice to avoid exceptions mechanism and to treat `MOVED`/`ASK` replies just like another type of reply. It means that `'Moved` and `'Ask` type constructors should be added to `Client.reply` type. 

In case of simple client usage this replies should be handled as errors, when using cluster client – these responses must be handled according to cluster specification.

Feel free to argue – I'm ready to discuss any concerns. If you need any help with design or implementation – feel free to ask, I'll try to help.

**Comment by Khady** [comment]
My work on cluster and mass insert is available there: https://github.com/ahrefs/ocaml-redis/tree/cluster

I don't really have time to cleanup everything now. But it may be interesting for some people. The cluster part was working without much problems for a small cluster of 20 nodes. And the mass insert gives big performance boost.

**Comment by aluuu** [comment]
Hello @Khady,

Great work. I've merged your changes and I'm going to release it in few days.

Thank you!

**Comment by aluuu** [comment]
I've created [PR](https://github.com/ocaml/opam-repository/pull/9212) to release redis with cluster support. 
Once it'll be closed – I'll close this issue.

**Comment by Khady** [comment]
Very nice from you to take care of this. Thank you!

**Comment by aluuu** [comment]
You are welcome. Package [has been released](http://opam.ocaml.org/packages/redis/redis.0.3.5/).
