### ISSUE TITLE
Publishing a new version

### ISSUE THREAD

**Issue by jlongster** [0xffea/ocaml-redis#47]
Any chance you could publish a new version to opam? Here are the new commits: https://github.com/0xffea/ocaml-redis/compare/a7a795e54b34745e9a7d3d02234ffbfd795b8798...2e1d49196eb4326ad85bb5bd2053a2ef7101da26

I'm interested in particular in my fix here: https://github.com/0xffea/ocaml-redis/commit/2e6858bbff6a61060f3118fbdf8316e55ef1a14a. The Lwt backend is broken without it.

**Comment by aluuu** [comment]
Hello @jlongster,

`redis.0.3.4` will be available soon, since [this PR](https://github.com/ocaml/opam-repository/pull/9200) has been merged.

Please, keep in mind that we moved to jbuilder and redis now split into three opam packages (`redis`, `redis-lwt` and `redis-sync`). Findlib names changed as well (`redis.lwt` became `redis-lwt`, for instance). So, don't forget to update your opam and build dependencies.
